Updated release versions for compose and helm
score-spec/docs pull request #82
Opened 2024-04-09 13:33 UTC by sujaya-sys

Thank you for submitting this pull request! We appreciate you spending the time to work on these changes.

Updated release versions for compose and helm

## Have you read the [Contributing Guidelines](CONTRIBUTING.md)?

- [x] I have read the [Contributing Guidelines](CONTRIBUTING.md)

2024-04-10 06:06 UTC, TobiasBabin requested changes
The download links need the version number updated in two places each. Please check the commit suggestions.

2024-04-10 06:06 UTC, TobiasBabin commented on content/en/docs/get started/included/install-score-compose-curl-mac.md
> +curl -L0 "https://github.com/score-spec/score-compose/releases/download/0.2.0/score-compose_0.12.2_darwin_arm64.tar.gz" -o score-compose.tgz
```suggestion
curl -L0 "https://github.com/score-spec/score-compose/releases/download/0.12.2/score-compose_0.12.2_darwin_arm64.tar.gz" -o score-compose.tgz
```

2024-04-10 06:06 UTC, TobiasBabin commented on content/en/docs/get started/included/install-score-helm-curl-mac.md
> +curl -L0 "https://github.com/score-spec/score-helm/releases/download/0.2.0/score-helm_0.9.0_darwin_arm64.tar.gz" -o score-helm.tgz
```suggestion
curl -L0 "https://github.com/score-spec/score-helm/releases/download/0.9.0/score-helm_0.9.0_darwin_arm64.tar.gz" -o score-helm.tgz
```

2024-04-11 08:57 UTC, sujaya-sys commented
Totally missed that 🤦‍♀️  Thanks Tobi!

2024-04-11 12:23 UTC, merged